site_name: async-zulip-bot-sdk
site_description: "Async Zulip Bot SDK documentation"
site_url: https://docs.llmvtuber.com/async-zulip-bot-sdk/
repo_url: https://github.com/Open-LLM-VTuber/async-zulip-bot-sdk/

docs_dir: docs
site_dir: site

nav:
  - Home: README.md
  - Quickstart: quickstart.md
  - Core:
      - Async client: async_client.md
      - Base bot: base_bot.md
      - Bot runner: bot_runner.md
      - Commands: commands.md
      - Config: config.md
      - Core: core.md
      - Logging: logging.md
      - Models: models.md
      - Storage: storage.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Quickstart: 快速开始
            Core: 核心组件
            Async client: 异步客户端
            Base bot: Bot 基类
            Bot runner: Bot 运行器
            Commands: 命令系统
            Config: 配置
            Logging: 日志
            Models: 数据模型
            Storage: 存储
